export type CuratedPillar = 'release' | 'activation' | 'range'
export type CuratedArea = 'hips' | 'shoulders' | 'spine'

export type CuratedRoutineExerciseTemplate = {
  name: string
  targetArea: CuratedArea
  sets: number
  reps: number | null
  holdSeconds: number | null
  rationale: string
  study: string
  aliases?: string[]
}

export const CURATED_ROUTINE_LIBRARY: Record<CuratedArea, Record<CuratedPillar, CuratedRoutineExerciseTemplate[]>> = {
  hips: {
    release: [
      {
        name: 'Kneeling Hip Flexor Stretch',
        targetArea: 'hips',
        sets: 1,
        reps: null,
        holdSeconds: 40,
        rationale: 'Reduces anterior hip stiffness before more active hip work. It is one of the most repeated release choices in your gym programs for opening extension.',
        study: 'Konrad et al. (2021). Effects of stretching training on range of motion. Sports Medicine.',
        aliases: ['Hip flexor kneeling', 'Kneeling hip front'],
      },
      {
        name: 'Quadruped Hamstring Stretch',
        targetArea: 'hips',
        sets: 1,
        reps: 6,
        holdSeconds: null,
        rationale: 'Opens posterior hip and hamstring tension without forcing a long static hold. It helps prepare hip flexion patterns before activation.',
        study: 'Behm et al. (2016). Acute effects of muscle stretching on physical performance. Applied Physiology, Nutrition, and Metabolism.',
        aliases: ['Quadruped ham stretch', 'Rocking hamstring'],
      },
      {
        name: 'Rocking Groin',
        targetArea: 'hips',
        sets: 1,
        reps: 8,
        holdSeconds: null,
        rationale: 'Targets adductors and groin tissues that often restrict lateral hip movement. It is a staple release drill across your hip sessions.',
        study: 'Page (2012). Current concepts in muscle stretching for exercise and rehabilitation. IJSPT.',
        aliases: ['Groiners', 'Rocking adductors'],
      },
      {
        name: 'Modified Pigeon',
        targetArea: 'hips',
        sets: 1,
        reps: null,
        holdSeconds: 40,
        rationale: 'Improves posterior hip and external rotation range before loading those positions. It consistently appears in your hip release blocks.',
        study: 'Konrad et al. (2021). Effects of stretching training on range of motion. Sports Medicine.',
        aliases: ['Pigeon', 'Modified pigeon 3 stances', 'Full pigeon'],
      },
      {
        name: '90/90 Hip Stretch',
        targetArea: 'hips',
        sets: 1,
        reps: null,
        holdSeconds: 35,
        rationale: 'Prepares internal and external rotation together so later hip work feels cleaner. It bridges your release and rotational activation pieces well.',
        study: 'Behm et al. (2016). Acute effects of muscle stretching on physical performance. Applied Physiology, Nutrition, and Metabolism.',
        aliases: ['90 90 stretch'],
      },
      {
        name: 'Deep Squat Shift',
        targetArea: 'hips',
        sets: 1,
        reps: 6,
        holdSeconds: null,
        rationale: 'Opens hips, groin, and ankles in a more athletic pattern than isolated stretching alone. It fits the way your release work often moves toward deeper loaded positions.',
        study: 'Cook et al. (2014). Movement: functional movement systems. On Target Publications.',
        aliases: ['Supported Deep Squat shifts', 'Deep squat shifts'],
      },
    ],
    activation: [
      {
        name: 'Resisted Seated External Rotation',
        targetArea: 'hips',
        sets: 2,
        reps: 8,
        holdSeconds: null,
        rationale: 'Builds active control of hip external rotation after opening the joint. It is one of your most repeated rotational hip activation drills.',
        study: 'Distefano et al. (2009). Gluteal muscle activation during common therapeutic exercises. JOSPT.',
        aliases: ['Seated banded 90/90 ER', 'Seated 90 90 ER'],
      },
      {
        name: 'Prone Hip Internal Rotation',
        targetArea: 'hips',
        sets: 2,
        reps: 8,
        holdSeconds: null,
        rationale: 'Strengthens internal rotation control where many athletes are weak or stiff. It matches your recurring prone IR activation work.',
        study: 'Casartelli et al. (2011). Gluteal muscle activation during common exercises. Journal of Electromyography and Kinesiology.',
        aliases: ['Prone IR', 'Prone foam roll IR', 'Resisted seated IR'],
      },
      {
        name: 'Supine In-Range Hip Flexion',
        targetArea: 'hips',
        sets: 2,
        reps: 8,
        holdSeconds: 2,
        rationale: 'Builds strength and control in hip flexion instead of relying on passive range only. This aligns with your repeated in-range flexor choices.',
        study: 'Oranchuk et al. (2019). Isometric training and its effects on strength and dynamic performance. Sports.',
        aliases: ['Supine in range Hip flex', 'Supine Hip flex', 'Full range hip flex'],
      },
      {
        name: 'Lateral Hip Abduction',
        targetArea: 'hips',
        sets: 2,
        reps: 8,
        holdSeconds: 2,
        rationale: 'Adds frontal-plane hip stability so the new range holds up under single-leg movement. It is one of your consistent hip activation staples.',
        study: 'Distefano et al. (2009). Gluteal muscle activation during common therapeutic exercises. JOSPT.',
        aliases: ['Banded lateral abductions', 'Lateral abduction', 'Lat AB duction'],
      },
      {
        name: '90/90 Shin Box Lift',
        targetArea: 'hips',
        sets: 2,
        reps: 6,
        holdSeconds: 2,
        rationale: 'Builds active hip rotational control in the same position you often mobilize later. This fits your progression from release into rotational strength.',
        study: 'Frazer et al. (2020). Mobility training and movement control. Sports Medicine.',
        aliases: ['90 90 Shin box', '90 90 isolated'],
      },
      {
        name: 'Single-Leg Glute Bridge',
        targetArea: 'hips',
        sets: 2,
        reps: 8,
        holdSeconds: null,
        rationale: 'Supports hip extension control and pelvic stability before range work. It mirrors the bridge variations in your activation sessions.',
        study: 'Distefano et al. (2009). Gluteal muscle activation during common therapeutic exercises. JOSPT.',
        aliases: ['SL glute bridge', 'Glute bridge'],
      },
    ],
    range: [
      {
        name: 'Heel Taps',
        targetArea: 'hips',
        sets: 2,
        reps: 6,
        holdSeconds: null,
        rationale: 'Challenges hip motion in a stronger, more end-range pattern than simple stretching. It is one of your most repeated hip mobilize drills.',
        study: 'Cook et al. (2014). Movement: functional movement systems. On Target Publications.',
      },
      {
        name: 'Standing Open-Close Hurdle',
        targetArea: 'hips',
        sets: 2,
        reps: 6,
        holdSeconds: null,
        rationale: 'Builds usable hip rotation and flexion in an upright athletic position. It matches your hurdle-based hip range work.',
        study: 'Frazer et al. (2020). Mobility training and movement control. Sports Medicine.',
        aliases: ['Standing open/close hurdle', 'Half kneeling hurdle open/close'],
      },
      {
        name: 'Standing Abducted Internal Rotation',
        targetArea: 'hips',
        sets: 2,
        reps: 6,
        holdSeconds: null,
        rationale: 'Loads hip internal rotation in a more sport-relevant standing position. This reflects your banded and supported rack IR work.',
        study: 'Cook et al. (2014). Movement: functional movement systems. On Target Publications.',
        aliases: ['Standing AB ducted IR', 'Rack IR', 'Wall ER/IR'],
      },
      {
        name: 'Quadruped Stiff-Leg Halo',
        targetArea: 'hips',
        sets: 2,
        reps: 6,
        holdSeconds: null,
        rationale: 'Integrates hip rotation and pelvic control through a larger range. It is one of the most consistent end-range drills in your hip programs.',
        study: 'Frazer et al. (2020). Mobility training and movement control. Sports Medicine.',
        aliases: ['Stiff leg halo', 'Long lever halo'],
      },
      {
        name: 'Wall Hip CARs',
        targetArea: 'hips',
        sets: 2,
        reps: 5,
        holdSeconds: null,
        rationale: 'Uses support to clean up end-range hip control without losing balance. It fits well as the stronger range expression after your release and activation work.',
        study: 'Frazer et al. (2020). Mobility training and movement control. Sports Medicine.',
        aliases: ['Wall cars', 'Wall/rack supported hip cars', 'Supported hurdle cars'],
      },
    ],
  },
  shoulders: {
    release: [
      {
        name: 'Prone Chest Slides',
        targetArea: 'shoulders',
        sets: 1,
        reps: 6,
        holdSeconds: null,
        rationale: 'Opens anterior shoulder and chest tissues before activation. It is one of your most repeated shoulder release choices.',
        study: 'Page (2012). Current concepts in muscle stretching for exercise and rehabilitation. IJSPT.',
        aliases: ['Chest slides', 'Pec slides', 'Side slides', 'Forward slides'],
      },
      {
        name: 'Shoulder Dives',
        targetArea: 'shoulders',
        sets: 1,
        reps: 6,
        holdSeconds: null,
        rationale: 'Helps free up shoulder flexion and front-of-shoulder stiffness through a smooth loaded stretch. It mirrors your dive and foam-roll push variations.',
        study: 'Behm et al. (2016). Acute effects of muscle stretching on physical performance. Applied Physiology, Nutrition, and Metabolism.',
        aliases: ['Dives', 'Foam roll pushes', 'Foam roll arm extensions'],
      },
      {
        name: 'Play Piano',
        targetArea: 'shoulders',
        sets: 1,
        reps: 8,
        holdSeconds: null,
        rationale: 'Targets lats and thoracic-shoulder linkage before overhead work. It appears repeatedly in your shoulder and mixed release sessions.',
        study: 'Page (2012). Current concepts in muscle stretching for exercise and rehabilitation. IJSPT.',
        aliases: ['Piano', 'Quaduped play the piano'],
      },
      {
        name: 'Quadruped Scapular Shrugs',
        targetArea: 'shoulders',
        sets: 1,
        reps: 8,
        holdSeconds: null,
        rationale: 'Reduces scapular stiffness and prepares the shoulder girdle for cleaner activation. It also bridges shoulder and spine sessions well.',
        study: 'Cools et al. (2007). Rehabilitation of scapular muscle balance. BJSM.',
        aliases: ['Scap work', 'On 4 shrugs'],
      },
    ],
    activation: [
      {
        name: 'Prone Stick to Traps',
        targetArea: 'shoulders',
        sets: 2,
        reps: 10,
        holdSeconds: null,
        rationale: 'Builds posterior shoulder and scapular support before bigger shoulder ranges. It is one of your most repeated shoulder activation drills.',
        study: 'Cools et al. (2007). Rehabilitation of scapular muscle balance. BJSM.',
        aliases: ['Prone stick WY', 'Prone scap squeezes'],
      },
      {
        name: 'Driver',
        targetArea: 'shoulders',
        sets: 2,
        reps: null,
        holdSeconds: 30,
        rationale: 'Creates shoulder and trunk control under low load before freer movement. It matches the driver drill you use in mixed shoulder-spine sessions.',
        study: 'McGill (2010). Core training: evidence translating to better performance and injury prevention. Strength and Conditioning Journal.',
      },
      {
        name: 'Flexion Extension Control',
        targetArea: 'shoulders',
        sets: 2,
        reps: 10,
        holdSeconds: null,
        rationale: 'Builds active control through shoulder flexion and extension before larger range drills. It is one of your repeated shoulder activation patterns.',
        study: 'Reinold et al. (2004). Electromyographic analysis of rotator cuff and deltoid musculature during common shoulder exercises. JOSPT.',
        aliases: ['Flex extens', 'Flex extension', 'Prone flex extension'],
      },
      {
        name: 'Plank Hand Taps',
        targetArea: 'shoulders',
        sets: 2,
        reps: 8,
        holdSeconds: null,
        rationale: 'Challenges closed-chain shoulder stability and scapular control. It shows up repeatedly in your shoulder activation blocks.',
        study: 'Ludewig et al. (2004). Relative balance of serratus anterior and upper trapezius muscle activity during push-up exercises. AJSM.',
        aliases: ['Plank steps', 'Plank w hand taps'],
      },
      {
        name: 'Banded T-V Raises',
        targetArea: 'shoulders',
        sets: 2,
        reps: 8,
        holdSeconds: null,
        rationale: 'Strengthens upward-rotation and posterior shoulder support before range work. It reflects your standing banded raise variations.',
        study: 'Cools et al. (2007). Rehabilitation of scapular muscle balance. BJSM.',
        aliases: ['Standing banded T-V raises', 'Standing banded Ys', 'T raises'],
      },
    ],
    range: [
      {
        name: 'Shoulder CARs',
        targetArea: 'shoulders',
        sets: 2,
        reps: 4,
        holdSeconds: null,
        rationale: 'Builds active shoulder rotation and full-circle control rather than passive flexibility alone. It is a staple of your shoulder mobility blocks.',
        study: 'Frazer et al. (2020). Mobility training and movement control. Sports Medicine.',
        aliases: ['Kneeling shoulder cars', 'Wall cars'],
      },
      {
        name: 'Floor Angel',
        targetArea: 'shoulders',
        sets: 2,
        reps: 8,
        holdSeconds: null,
        rationale: 'Integrates shoulder range with thoracic position and scapular control. It appears repeatedly as one of your preferred range drills.',
        study: 'Cools et al. (2007). Rehabilitation of scapular muscle balance. BJSM.',
      },
      {
        name: 'Alternate Swimmer',
        targetArea: 'shoulders',
        sets: 2,
        reps: 5,
        holdSeconds: null,
        rationale: 'Links overhead shoulder motion with upper-back control in a longer, more active pattern. It is one of your signature mobility choices.',
        study: 'Manske et al. (2013). Current concepts in shoulder examination and treatment. IJSPT.',
        aliases: ['Swimmers', 'Handcuffed swimmer'],
      },
      {
        name: 'Floor Rainbow',
        targetArea: 'shoulders',
        sets: 2,
        reps: 5,
        holdSeconds: null,
        rationale: 'Challenges shoulder range with thoracic rotation instead of isolating one joint. It appears frequently in your mixed shoulder-spine work.',
        study: 'Cook et al. (2014). Movement: functional movement systems. On Target Publications.',
        aliases: ['Wall rainbow to archer', 'Banded archers'],
      },
    ],
  },
  spine: {
    release: [
      {
        name: 'Seal Stretch',
        targetArea: 'spine',
        sets: 1,
        reps: 6,
        holdSeconds: null,
        rationale: 'Opens the anterior chain and encourages spinal extension before more active rotation work. It shows up constantly in your spine flows.',
        study: 'Page (2012). Current concepts in muscle stretching for exercise and rehabilitation. IJSPT.',
        aliases: ['Seal', 'Prone seal to child'],
      },
      {
        name: 'Scorpio',
        targetArea: 'spine',
        sets: 1,
        reps: 6,
        holdSeconds: null,
        rationale: 'Brings trunk rotation and anterior chain opening together in a dynamic release pattern. It is a core part of many of your spine release sessions.',
        study: 'Behm et al. (2016). Acute effects of muscle stretching on physical performance. Applied Physiology, Nutrition, and Metabolism.',
        aliases: ['Scorpion', 'Prone Scorpions'],
      },
      {
        name: 'Cat-Cow',
        targetArea: 'spine',
        sets: 1,
        reps: 8,
        holdSeconds: null,
        rationale: 'Improves spinal segmentation and reduces stiffness before stronger work. It is one of the most repeated spine release drills across your programs.',
        study: 'McGill (2010). Core training: evidence translating to better performance and injury prevention. Strength and Conditioning Journal.',
      },
      {
        name: 'QL Standing Stretch',
        targetArea: 'spine',
        sets: 1,
        reps: null,
        holdSeconds: 30,
        rationale: 'Targets side-body and trunk stiffness that can interfere with rotation and side flexion. It fits your repeated QL-focused release work.',
        study: 'Page (2012). Current concepts in muscle stretching for exercise and rehabilitation. IJSPT.',
        aliases: ['QL', 'Frame QL', 'Kneel side flex'],
      },
      {
        name: 'Supine Knee Rocks',
        targetArea: 'spine',
        sets: 1,
        reps: 8,
        holdSeconds: null,
        rationale: 'Gently restores rotational movement and reduces trunk stiffness without aggressive loading. It fits the early release tone of your mixed sessions.',
        study: 'Behm et al. (2016). Acute effects of muscle stretching on physical performance. Applied Physiology, Nutrition, and Metabolism.',
      },
    ],
    activation: [
      {
        name: 'Bird Dog',
        targetArea: 'spine',
        sets: 2,
        reps: 6,
        holdSeconds: null,
        rationale: 'Builds cross-body trunk control so spinal motion stays clean and supported. It is one of your most repeated spine activation drills.',
        study: 'McGill (2010). Core training: evidence translating to better performance and injury prevention. Strength and Conditioning Journal.',
      },
      {
        name: 'Superman',
        targetArea: 'spine',
        sets: 2,
        reps: 10,
        holdSeconds: null,
        rationale: 'Develops posterior chain and trunk extension support after release work. It appears repeatedly in your spine activation blocks.',
        study: 'Ekstrom et al. (2007). Surface electromyographic analysis of trunk muscle activation during stabilization exercises. Journal of Orthopaedic and Sports Physical Therapy.',
      },
      {
        name: 'Full Dead Bug',
        targetArea: 'spine',
        sets: 2,
        reps: 10,
        holdSeconds: null,
        rationale: 'Improves trunk control and helps keep new mobility from leaking into unwanted lumbar movement. It pairs well with your bird dog and superman sequence.',
        study: 'McGill (2010). Core training: evidence translating to better performance and injury prevention. Strength and Conditioning Journal.',
        aliases: ['Dead bug', 'Banded deadbug'],
      },
    ],
    range: [
      {
        name: 'In and Outs',
        targetArea: 'spine',
        sets: 2,
        reps: 5,
        holdSeconds: null,
        rationale: 'Loads spinal and trunk range with more active control than simple mobility drills. It is part of your repeated spine mobility trios.',
        study: 'Cook et al. (2014). Movement: functional movement systems. On Target Publications.',
      },
      {
        name: 'Floor Rainbow',
        targetArea: 'spine',
        sets: 2,
        reps: 5,
        holdSeconds: null,
        rationale: 'Trains trunk rotation and shoulder-spine linkage through active range. It is one of your signature mixed spine mobility drills.',
        study: 'Cook et al. (2014). Movement: functional movement systems. On Target Publications.',
      },
      {
        name: 'Side Plank with T Rotation',
        targetArea: 'spine',
        sets: 2,
        reps: 5,
        holdSeconds: null,
        rationale: 'Adds real strength to spinal rotation and side-body control at end range. It matches your definition of range as strong mobility.',
        study: 'McGill (2010). Core training: evidence translating to better performance and injury prevention. Strength and Conditioning Journal.',
        aliases: ['Side plank w T'],
      },
      {
        name: 'Quadruped T Rotation',
        targetArea: 'spine',
        sets: 2,
        reps: 5,
        holdSeconds: null,
        rationale: 'Builds thoracic rotation while keeping the hips and lumbar spine controlled. It is a recurring spine mobility drill in your programs.',
        study: 'Cook et al. (2014). Movement: functional movement systems. On Target Publications.',
        aliases: ['Quadruped spine T rotation', 'T rotation', 'Thoracic rot short'],
      },
    ],
  },
}

export function buildApprovedExercisePoolText(targetAreas: string[]) {
  const safeAreas = targetAreas.filter((area): area is CuratedArea =>
    Object.prototype.hasOwnProperty.call(CURATED_ROUTINE_LIBRARY, area),
  )
  const areas: CuratedArea[] = safeAreas.length > 0 ? safeAreas : ['hips', 'shoulders', 'spine']

  return areas
    .map((area) => {
      const phases = CURATED_ROUTINE_LIBRARY[area]
      return [
        `${area.toUpperCase()}:`,
        `release -> ${phases.release.map((exercise: CuratedRoutineExerciseTemplate) => exercise.name).join(', ')}`,
        `activation -> ${phases.activation.map((exercise: CuratedRoutineExerciseTemplate) => exercise.name).join(', ')}`,
        `range -> ${phases.range.map((exercise: CuratedRoutineExerciseTemplate) => exercise.name).join(', ')}`,
      ].join('\n')
    })
    .join('\n\n')
}
